build: off

image:
  - Visual Studio 2019

environment:
  global:
    STACK_ROOT: "c:\\sr"

  matrix:
    - ARGS: ""
    - ARGS: "--resolver lts-12"
    - ARGS: "--resolver lts-13"
    - ARGS: "--resolver lts-14"
    - ARGS: "--resolver lts-15"
    - ARGS: "--resolver lts-16"
    - ARGS: "--resolver nightly"

clone_folder: "c:\\stack"

before_test:
  # Override the temp directory to avoid sed escaping issues
  # See https://github.com/haskell/cabal/issues/5386
  - set TMP=C:\tmp

  # http://help.appveyor.com/discussions/problems/6312-curl-command-not-found
  - set PATH=C:\Program Files\Git\mingw64\bin;%PATH%
  - curl -sS -ostack.zip -L --insecure https://get.haskellstack.org/stable/windows-x86_64.zip
  - 7z x stack.zip stack.exe

test_script:
  # Install toolchain, but do it silently due to lots of output
  - stack %ARGS% setup > nul
  # The ugly echo "" hack is to avoid complaints about 0 being an invalid file
  # descriptor
  - echo "" | stack %ARGS% --no-terminal test
