build: off

image:
  - Visual Studio 2019

environment:
  global:
    STACK_ROOT: "c:\\sr"

  matrix:
    # - ARGS: "--resolver lts-12" # We support ghc-8.4, but this particular build fails due to cabal compatibility issues
    - ARGS: "--resolver lts-13" # ghc-8.6.4
    - ARGS: "--resolver lts-14" # ghc-8.6.5
    - ARGS: "--resolver lts-15" # ghc-8.8.2
    - ARGS: "--resolver lts-16" # ghc-8.8.4
    - ARGS: "--resolver nightly"

clone_folder: "c:\\stack"

before_test:
  # http://help.appveyor.com/discussions/problems/6312-curl-command-not-found
  - set PATH=C:\Program Files\Git\mingw64\bin;%PATH%
  - curl -sS -ostack.zip -L --insecure https://get.haskellstack.org/stable/windows-x86_64.zip
  - 7z x stack.zip stack.exe

test_script:
  # Install toolchain, but do it silently due to lots of output
  - stack %ARGS% setup > nul
  # The ugly echo "" hack is to avoid complaints about 0 being an invalid file
  # descriptor
  - echo "" | stack %ARGS% --no-terminal test
